version: '3.4'

services:
    db:
        image: mysql:8.0
        command: ["--default-authentication-plugin=mysql_native_password"]
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony

    adminer:
        image: adminer
        restart: on-failure
        ports:
            - 8080:8080

    php:
        build:
            context: ./
            target: app_php
            dockerfile: Dockerfile
        environment:
            - APP_ENV=dev
        ports:
            - 9000:9000
        volumes:
            - ./:/srv/app:rw,cached
            - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.ini
        depends_on:
            - db

    nginx:
        build:
            context: ./
            target: app_nginx
        ports:
            - 80:80
        depends_on:
            - php
        volumes:
            - ./web:/srv/app/web:ro

    blackfire:
        image: blackfire/blackfire
        env_file:
            - blackfire-variables.env

